#!/usr/bin/env bash

java -jar compiler.jar                         \
	--language_in ECMASCRIPT_2015              \
	--language_out ECMASCRIPT5                 \
	--js js/Matrix/Cells.js                    \
	--js js/Matrix/Model.js                    \
	--externs js/extRouter.js                  \
	--compilation_level SIMPLE_OPTIMIZATIONS   \
	--js_output_file public/matrix.smp.js
